package testNG.P_Reports.DefaultReports;

public class Introduction
{
    /**
     * Default reports generated by TestNG.
     *
     * What is meant by reports?
     * Overview of TestNG default reports?
     * Do we really use TestNG default reports?
     *
     */

    /**
     * What is meant by reports and why do we need them?
     *
     * When ever we are executing our test we have to track our test execution like which tests are passed and which are
     * failed and what are exceptions occurred when a test is failed, we need to track all these, information like how many
     * are passed how many are failed and how many are skipped.
     *
     * We will get information like what is pass percentage of our tests which we are executed only from the test reports.
     *
     * We can track them in console of the IDE also but, we will some issues while tracking them in the IDE console,
     * let's look into those issues.
     *
     * We can see the results of all executed tests in console of IDE but, we can't find the execution time of the
     * test in the console.
     *
     * So console is not helpful to find the test execution time, we can find them by using TestNG console where we can
     * find the test passed, failed, passed, skipped and the time taken by each test to execute etc... if this is the case
     * if we are finding all the details then what is the use of TestNG reports that provided by TestNG?
     *
     * Let's take this scenario:
     *
     * Suppose we have run our 1000 test cases and which takes 1000 minutes approximately and there-after, we have to
     * show results of our tests to our manager or lead, but I have switch-off my system where I'm unable to view my
     * test status in console of TestNG, so to overcome these types of issues developers have introduced reports concept
     * in the test execution where we can view the status of the reports even after some days of test execution.
     *
     * What are different types of reports do we have in testing?
     *
     * We can generate any kind of reports like XML, Excel, Doc, html etc... based on our requirement.
     */

    /**
     * Does TestNG generate any kind of reports by default?
     *
     * Yes by default TestNG will generate reports without any configuration.
     *
     * By default, TestNG will generate reports inside the project
     */

    /**
     * Do we really use TestNG reports in Organizations?
     *
     * No, TestNG reports provide very basic features and UI is also not up-to the organization standards so
     * Organizations prefer other reports which provide Reach UI and advanced features like, Filtering etc...
     *
     * We are going to use reports like Extent and Allure reports in organizations.
     */
}
